# API Gateway Local Configuration
server:
  port: 9999

spring:
  application:
    name: GATEWAY-API
 
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-api/**
          filters:
            - StripPrefix=0

        - id: PACKAGE-SERVICE
          uri: lb://PACKAGE-SERVICE
          predicates:
            - Path=/api/packages/**
          filters:
            - StripPrefix=0

        - id: BOOKING-SERVICE
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=0

        - id: PAYMENT-SERVICE
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=0

        - id: INSURANCE-SERVICE
          uri: lb://INSURANCE-SERVICE
          predicates:
            - Path=/api/insurance/**
          filters:
            - StripPrefix=0

        - id: ASSISTANCE-SERVICE
          uri: lb://ASSISTANCE-SERVICE
          predicates:
            - Path=/api/assistance/**
          filters:
            - StripPrefix=0

        - id: REVIEW-SERVICE
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/reviews/**
          filters:
            - StripPrefix=0
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true